name: artifact
on: [push]
run-name: ubuntu-latest
env:
  ARTIFACT_NAME: myartifact
jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
      - name: this is artifact 
        uses: actions/checkout@v4.2.2
      - name: artifact
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: ${{ env.ARTIFACT_NAME }}
          path: .
    
